# Generated by Django 5.2.6 on 2025-09-28 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.BigIntegerField(db_index=True, verbose_name='UID')),
                ('folder', models.CharField(db_index=True, default='INBOX', max_length=50, verbose_name='Folder')),
                ('subject', models.CharField(blank=True, db_index=True, max_length=500)),
                ('sender', models.CharField(blank=True, db_index=True, max_length=200)),
                ('receiver', models.CharField(blank=True, max_length=200)),
                ('cc', models.JSONField(blank=True, default=list)),
                ('date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_seen', models.BooleanField(default=False)),
                ('is_flagged', models.BooleanField(default=False)),
                ('text', models.TextField(blank=True)),
                ('html', models.TextField(blank=True)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '邮件',
                'verbose_name_plural': '邮件',
                'indexes': [models.Index(fields=['folder', 'date'], name='api_email_folder_1949a4_idx'), models.Index(fields=['folder'], name='api_email_folder_9f788a_idx')],
                'unique_together': {('uid', 'folder')},
            },
        ),
    ]
