# Generated by Django 5.2.6 on 2025-10-01 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='receiver',
            new_name='form',
        ),
        migrations.RenameField(
            model_name='email',
            old_name='sender',
            new_name='to',
        ),
        migrations.RemoveField(
            model_name='email',
            name='is_flagged',
        ),
        migrations.RemoveField(
            model_name='email',
            name='is_seen',
        ),
        migrations.AddField(
            model_name='email',
            name='bcc',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='email',
            name='size',
            field=models.IntegerField(default=0),
        ),
    ]
