# Generated by Django 5.2.6 on 2025-10-01 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_receiver_email_form_rename_sender_email_to_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='form',
            new_name='from_email',
        ),
    ]
