# Generated by Django 5.2.6 on 2025-10-04 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_form_email_from_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='from_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
